### ISSUE TITLE
Full theming

### ISSUE THREAD

**Issue by Boiiterra** [EvgenHi/math_multiplication_trainer#4]
Hello, is it possible to change colors of this numbers that are shown on the image below?
[![image](https://user-images.githubusercontent.com/81579070/194036555-2dedc400-e585-4516-bea1-9ae24d4ba13c.png)]()

**Comment by Boiiterra** [comment]
Another issue is input block:
[![image](https://user-images.githubusercontent.com/81579070/194038871-356e340b-4573-49cf-adf2-ac8d2d5922fd.png)]()
You can change border color, but not the inner part (dark one).

**Comment by EvgenHi** [comment]
Functionality added in this commit [this](https://github.com/EvgenHi/math_multiplication_trainer/commit/9bd637ca7005036cd844f7bf3ef7ae53fed05f22) commit.
